DROP DATABASE IF EXISTS `myproject`;
CREATE DATABASE `myproject` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

USE 'myproject';
GRANT ALL PRIVILEGES ON django_db1.* TO 'aris'@'localhost' IDENTIFIED BY 'aris1!'

WITH GRANT OPTION;
FLUSH PRIVILEGES;
